In [3]:
# python packages
import matplotlib.pyplot as plt
import scipy
from scipy import stats
import numpy as np
import pandas as pd
from datetime import datetime as dt
from sklearn.model_selection import train_test_split
import torch
from torch import nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import json
import xarray as xr

# my imports
import prop_data_prep as pdp
import prop_nn_models as pnn
import prop_nn_functions as pnf
import prop_MCDO_functions as MCDO
import prop_visualizations as viz
from prop_mms_data_prep import write_toDf, sweep

## MODEL LOADING

In [4]:
# model params
# inputs t0, te, imef_data
# assume nans removed

# load model
model_floc = "prop_models/"  # directory to save model
model_fname = "ANN_complete_EXYZ"  # sample model
model_path = model_floc + model_fname  # full model path

# load train/test dataset (want to use test data in futr maybe?)
imef_data = pd.read_pickle("prop_models/complete_training_df")
time_indx = imef_data.index.values[100:160]  # "test times"

# load hyperparameter configuration
f = open(model_path + "_config.json")
CONFIG = json.load(f)

# initialize the model
model = pnn.FeedForwardNN_MCDO(
    CONFIG["num_features"],
    CONFIG["seq_len"],
    CONFIG["hidden_size"],
    CONFIG["output_size"],
    CONFIG["dropout_prob"],
)
model.load_state_dict(torch.load(model_floc + model_fname))

predictors = [
    "OMNI_IMF",
    "OMNI_Vx",
    "OMNI_Vy",
    "OMNI_Vz",
    "OMNI_SYM_H",
    "L",
    "MLAT",
    "MLT",
]  # predictors, features
target = ["EX", "EY", "EZ"]

# separate swolar wind (swi) and location (loc) predictors
#   - this will be used to index and assemble matrix correctly
swi_predictors = predictors[:5]  # solar wind predictors
loc_predictors = predictors[5:]  # location (L,MLT, MLAT) predictors

## CREATE DESIGN MATRIX


In [40]:
"""
Assemble Design Matrix
for Izzak's code, see
    - imef/efield/model_creation/NN_functions.py 
        - (get_NN_inputs function!)

"""

design_matrix = []  # list to hold desigh matrix
time_matrix = []  # list to hold times assoc. with matrix values

for ix in range(0, len(time_indx)):
    ix_matrix_row = []  # matrix row at loop index (ix)

    # get time intervals
    # `- (!) should be end??
    time_intervals = pd.date_range(end=time_indx[ix], freq="5T", periods=60) # maybe min scales?
    # print('index',time_indx)
    # print('intrvl',time_intervals)
    # try:
    # write predictors at ix to row

    # loop through each swind predictor and append it to matrix
    for swi_var in swi_predictors:
        # pull predictor from dataset as xarray
        swi_xarr = imef_data[swi_var].to_xarray()

        # split data in interval format and append to design matrix row
        ix_arr = swi_xarr.sel(time=time_intervals, method="nearest").values.tolist()
        ix_matrix_row += ix_arr  

    # get location data (L, MLT, MLAT) and assemble into matrix format
    loc_data = np.array(
        [
            imef_data["L"].values[ix],
            np.cos(np.pi / 12 * imef_data["MLT"].values[ix]),
            np.sin(np.pi / 12 * imef_data["MLT"].values[ix]),
            np.cos(imef_data["MLAT"].values[ix]),
            np.sin(imef_data["MLAT"].values[ix]),
        ]
    )

    print(imef_data["L"].values[ix])

    # write location data (np array) at ix to row (list)
    ix_matrix_row += loc_data.tolist()

    # append row to design matrix
    # print("row",ix_matrix_row)
    design_matrix.append(ix_matrix_row)

    # append times to time matrix
    time_matrix.append(time_indx[ix])

# torch tensor design matrix
design_matrix_tensor = torch.tensor(design_matrix)

# np array design matrix 
design_matrix_arr = np.array(design_matrix)

# except Exception as ex:
#     pass

9.796475937539341
9.78054494084098
9.764557008063449
10.27472622865742
10.29713068705834
10.319457497428042
9.7753878239563
9.759309599513628
9.743174034259292
9.79937551291163
9.783319725201748
9.76720715280763
9.751037526772269
9.73616676957596
9.718525774767068
10.292827977536419
9.791609421117965
9.775463218137455
9.759260171674233
9.742999939036828
9.799770690433972
9.734707446727823
9.71829843136164
9.807464615126909
10.341517636849003
10.364529131400724
10.38746396148276
9.781942922505943
9.76557490424617
9.749150009467561
9.732667940299722
11.078089685599195
11.065803657779151
11.053481071304583
11.04112178781822
11.028725636005499
11.098394122111005
11.085994572174902
11.073558703391688
11.061086309586912
11.048577282312962
11.03603143423023
14.078295465085406
14.07629057381014
14.074246129741516
14.070039298273104
14.05166510761242
14.046691768028966
14.036298892197422
12.973779460455619
12.59035732319598
14.094489169029833
12.968763470907271
11.960134777569609
11.65165192278

In [37]:
nL = 10 # number of bins for L
nMLT = 24 # number of bins for MLT
nMLAT = 10 # number of bins for MLAT

# total bin rows in matrix slice (single time)
nrows_total = nL*nMLT*nMLAT

# (!)get non-location based predictors
# base_values = design_matrix_tensor[-1].clone()

base_values = design_matrix_tensor[0:len(swi_predictors),:].clone()

# set up array
# shape should be (nL*nMLT*nMLAT, number of predictors)
dmatrix = np.zeros([nrows_total, len(predictors)])

dm_indx = 0
for i_L in range(0,nL):
    for i_MLT in range(0,nMLT):
        for i_MLAT in range(0,nMLAT):

        # dmatrix[dm_indx, -3] = l_bins[i] # L
        # dmatrix[dm_indx, -2] = mlt_bins[j] # MLT
        # dmatrix[dm_indx, -1] = mlat_bins[k] # MLAT

            # location predictors 
            dmatrix[dm_indx, -5] = i_L # L
            dmatrix[dm_indx, -4] = np.cos(np.pi / 12 * i_MLT) # cos(MLT)
            dmatrix[dm_indx, -3] = np.sin(np.pi / 12 * i_MLT) # sin(MLT)
            dmatrix[dm_indx, -2] = np.cos(i_MLAT) # cos(MLAT)
            dmatrix[dm_indx, -1] = np.sin(i_MLAT) # sin(MLAT)

            dm_indx += 1 # raise deign matrix index


# convert to torch tensor
# [...]

# test model
# model.eval()
# with torch.no_grad():
#     pred = model(all_locations)


In [52]:
x = np.arange(10)
np.repeat(x[:,np.newaxis], 5, axis=1)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9]])

In [13]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.zeros([2,4])
print (a)
print(b)

b[:,0:3] = a[0,0:3]
print(b)


[[1 2 3 4]
 [5 6 7 8]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 2. 3. 0.]
 [1. 2. 3. 0.]]


In [30]:
"""
for Izzak's code, see
    - imef/data_manipulation.py
    - visualizations/plot_nc_data.py
    - imef/efield/model_creation/NN_functions.py
    - imef/data/database.py
        - **(predict_efield_and_potential function!)

"""

number_of_inputs = len(swi_predictors)  # number of inputs/predictors

# unsure how to adjust this for all predicors? is this grabbing row or column?
# izzak used:
#   >> base_kp_values = design_matrix_tensor[-1].clone()
# my variation (I don't know what to do for this):
base_values = design_matrix_tensor[-1].clone()

# izzak used:
#   >> size_of_input_vector = 60 * number_of_inputs + 3
# my variation:
size_of_input_vector = 60 * number_of_inputs + 5

# I THINK this is izzak's way of setting up the matrix to be accepted
# by the model, but...its not clear.
for L in range(4, 11):
    for MLT in range(0, 24):
        new_row = base_values.clone()
        # new_row[:-3]
        new_row[-3] = L
        new_row[-2] = np.cos(np.pi / 12 * MLT)
        new_row[-1] = np.sin(np.pi / 12 * MLT)
        even_newer_row = torch.empty((1, size_of_input_vector))
        even_newer_row[0] = new_row
        if L == 4 and MLT == 0:
            all_locations = even_newer_row
        else:
            all_locations = torch.cat((all_locations, even_newer_row))

model.eval()
with torch.no_grad():
    pred = model(all_locations)

# row1 

RuntimeError: shape '[168, 480]' is invalid for input of size 51240

# Plotting (TBD)

In [26]:
base_values = design_matrix_tensor[design_matrix_tensor.columns[-3:]]

AttributeError: 'Tensor' object has no attribute 'columns'